name = "Estrogen"
author = "Joshua"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee61af64d4aeddff6f716b66526b23dbaab73b7201b72a9bc636b661bbd0a6f5"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
