name = "Estrogen"
author = "Joshua"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8db3e7b4e1965852d949fa43343dec4675dc1b42918561d64bd86c31812bed2e"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
