name = "Estrogen"
author = "Joshua"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbd5cfa46136f1c0afa1e30ca4730f21fdddeef55ce592537dc59ff57ad47513"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
