#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 19 12:10:43 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=
